//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Police.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.OpenCase = new HashSet<OpenCase>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdLevel { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdCrimeType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CrimeType CrimeType { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpenCase> OpenCase { get; set; }
    }
}
