//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Police.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliceEntities : DbContext
    {
        public PoliceEntities()
            : base("name=PoliceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CrimeType> CrimeType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<OpenCase> OpenCase { get; set; }
        public virtual DbSet<Rang> Rang { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
